### ISSUE TITLE
sapphire: encrypted contract create not recognized as encrypted

### ISSUE THREAD

**Issue by pro-wh** [oasisprotocol/nexus#445] opened 2023-06-12 17:49 UTC
we try to decode the result as cbor, but it's an address (?)

**Comment by matevz** [comment] 2023-08-25 14:28
I can confirm this bug. Steps to reproduce, if anyone interested:

1. Deploy a smart contract using an encrypted transaction by including `require('@oasisprotocol/sapphire-hardhat');` in the beginning of the hardhat config.
2. The transaction appears in explorer, but is marked as unencrypted: https://explorer.dev.oasis.io/testnet/sapphire/tx/0xb2ab98468dd320804a3ead5fc10f4bda85c11cfe3bce7232f2d59e91d74788dc
![image](https://github.com/oasisprotocol/explorer/assets/83672/608a2b6c-d1e4-4c56-82d0-1af1a82c8daa)
4. The transaction is clearly encrypted, see https://testnet.explorer.sapphire.oasis.dev/tx/0xb2ab98468dd320804a3ead5fc10f4bda85c11cfe3bce7232f2d59e91d74788dc which you can decode with CBOR and get
```
{"body": {"pk": h'A66E9628F7E64814F179C4B8BF7E8958BDC38E0EF2EA3C5E18D6ADC9690A913B', "data": h'56C7AE0F8FDAB6E413D426ABE48695ADB128BAE97E3C36351BAA3BE4E03EE5A7E7A4936ECF4A545824BCA5FEEF07B4F84502B24BDC71B1919FFAA7A6FB31B498FBF706BFE4EDB71E2081176BFB309EC4F052DB26C81C890C417F880D6FDFB5AD6B6440658DDCD667BB8FF89755B48086C165CAFBFF659772897FEC17D09AE5707FFE29A1D3F8D98A27209B9F1C45EDA62CD82BD117C7ABFFB061D8D6E48F9685983B61239829A3E090FA36ACE162B61F53AE2BC489F3D4134315550DD86FF5EAE9D74457F79B4068E591B25BEBECB405773A3673786CD5A996B7E2E896E7E00FF7AD070813039823EE56DF0BEC803C75E6437EBCB1FCF6152B7909C5A711171D7755B6744D606E4AC40198042F7B02C5E5B1785EF60E571B64B0078A608E4E5ADCAC58CE1ACCA6A4640F4342A742D1E50FC65B33A0149EF485A2B192E677B3C1415E417BF58CFBA3B0AFF51FF3C24D91AAAC21C9E77FCE65451FB42447813F25D80E1370BD95300492EAB150E2E95CFD72708F7178E8099BC60A4709FDB371326B6C48433E263C3A6A', "nonce": h'46EB621D1DC131EB5B8A8829C21F2E'}, "format": 1}
```

**Comment by matevz** [comment] 2023-08-25 14:36
Interesting, this contract create transaction failed, but was correctly recognized as encrypted: https://explorer.dev.oasis.io/testnet/sapphire/tx/0x7690a6e96985aa349608d07e0f68f7bd7253bb8a5495a3df1db3c2fc224bb3fe

However, the data (encrypted) is not cbor-decodable.

**Comment by kostko** [comment] 2023-08-25 20:48
> However, the data (encrypted) is not cbor-decodable.

This is because it is decoding the envelope and showing the encrypted payload as the "data" (in contrast to the other block explorer which does not know anything about envelopes so it is showing the envelope as the "data").

**Comment by Andrew7234** [comment] 2023-09-24 07:39
Looks like during the early days of testnet there are some encrypted sapphire evm.Create txs that have a cbor-encoded `callResult`. There are 360 of these txs ranging from blocks 2293->5023 on testnet. [Sample tx](https://explorer.dev.oasis.io/testnet/sapphire/tx/0x669d9e79702eef3b1347f7b846331dab0bc0751f3859b42dc998a432147e9c4a)
Sample callResult: 
```{"unknown": {"data": h'F84C1B6FED3EAA0DB23987A64ECF06A55A333BCE44C1FAF45D4B97A18017670F8F5EDA85CDB7CA0C69', "nonce": h'00000000000008F400000000000000'}}
```

In addition, there are some strange cases after that where we have encrypted sapphire evm.Create txs where the result is an address, but it successfully cbor-decodes into an empty `callResult`. There are 27 of these txs ranging from block 5253 -> 2698448 on testnet. [Sample tx](https://explorer.dev.oasis.io/testnet/sapphire/tx/0x590e6d5c9ae432cd3402be71edece07240a615dc70200e8f7491d9cf34c80dd7)

I believe there are also 4 cases of this on mainnet, though I haven't verified with the node yet. [Sample tx](https://explorer.dev.oasis.io/mainnet/sapphire/tx/0x735693f6b97bcfc64bd7a2568a5ccf1f7a3c95e843f46a9c4d7220ed34a3ffae). The rest of the evm.Create calls on Sapphire mainnet weren't recognized as being encrypted.

Apart from the exceptions mentioned above, is it correct to say that successful `evm.Create` calls will always return an address of the created contract? And can we expect failed `evm.Create` calls to always return a nil result?

**Closed** 2023-09-26 01:18 UTC
Labels: bug, analysis-layer
